services:
  - type: web
    name: darija-app
    env: node
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start -p $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    autoDeploy: true
    plan: free