services:
  - type: web
    name: darija-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: NODE_OPTIONS
        value: --max-old-space-size=200
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    autoDeploy: true
    plan: free